// Generated by CoffeeScript 1.4.0
(function() {
  var AUTH, ROOMID, USERID;

  AUTH = 'XXXXXX';

  USERID = 'XXXXXX';

  ROOMID = 'XXXXXX';

  exports.AUTH = AUTH;

  exports.USERID = USERID;

  exports.ROOMID = ROOMID;

}).call(this);
