// Generated by CoffeeScript 1.4.0
(function() {
  var bot, chatToSend, sendChat, sendChatMessage, setBot;

  chatToSend = [];

  bot = null;

  setBot = function(_bot) {
    return bot = _bot;
  };

  sendChat = function(msgs) {
    var msg, numInQueue, _i, _len;
    numInQueue = chatToSend.length;
    for (_i = 0, _len = msgs.length; _i < _len; _i++) {
      msg = msgs[_i];
      chatToSend.push(msg);
    }
    if (numInQueue === 0) {
      return sendChatMessage();
    }
  };

  sendChatMessage = function() {
    var msgToSend;
    if (chatToSend.length === 0) {
      return;
    }
    msgToSend = chatToSend.shift();
    return setTimeout(function() {
      console.log('chat: ' + msgToSend);
      return bot.speak(msgToSend, sendChatMessage);
    }, 100);
  };

  exports.setBot = setBot;

  exports.sendChat = sendChat;

}).call(this);
