// Generated by CoffeeScript 1.6.3
(function() {
  var getActiveCount, latestUserActions, logUserAction, pruneUsers, setVotersActive;

  latestUserActions = {};

  logUserAction = function(userid) {
    return latestUserActions[userid] = new Date().getTime();
  };

  getActiveCount = function(activeTime) {
    var now, numActive, time, timeAgo, userid;
    now = new Date().getTime();
    timeAgo = now - activeTime;
    numActive = 0;
    for (userid in latestUserActions) {
      time = latestUserActions[userid];
      if (time > timeAgo) {
        numActive++;
      }
    }
    return numActive;
  };

  pruneUsers = function() {
    var idsToDelete, now, pruneLimit, pruneTime, time, userid, _i, _len, _results;
    now = new Date().getTime();
    pruneLimit = 60 * 60 * 1000;
    pruneTime = now - prumeLimit;
    idsToDelete = [];
    for (userid in latestUserActions) {
      time = latestUserActions[userid];
      if (time < pruneTime) {
        idsToDelete.push(userid);
      }
    }
    _results = [];
    for (_i = 0, _len = idsToDelete.length; _i < _len; _i++) {
      userid = idsToDelete[_i];
      _results.push(delete latestUserActions[userid]);
    }
    return _results;
  };

  setVotersActive = function(voters) {
    var vote, _i, _len, _results;
    return;
    console.log(latestUserActions);
    console.log(voters);
    _results = [];
    for (_i = 0, _len = voters.length; _i < _len; _i++) {
      vote = voters[_i];
      _results.push(logUserAction(vote[0]));
    }
    return _results;
  };

  exports.logUserAction = logUserAction;

  exports.getActiveCount = getActiveCount;

  exports.pruneUsers = pruneUsers;

  exports.setVotersActive = setVotersActive;

}).call(this);
