// Generated by CoffeeScript 1.3.3
(function() {
  var del, get, init, redisClient, set;

  redisClient = null;

  init = function(redis) {
    return redisClient = redis;
  };

  get = function(userid, cb) {
    return redisClient.get("PIN-" + userid, function(error, json) {
      if (json === null) {
        return cb(error, null);
      } else {
        return cb(error, JSON.parse(json));
      }
    });
  };

  set = function(userid, pin, cb) {
    if (cb == null) {
      cb = null;
    }
    return redisClient.set("PIN-" + userid, JSON.stringify(pin));
  };

  del = function(userid, cb) {
    if (cb == null) {
      cb = null;
    }
    return redisClient.del("PIN-" + userid, cb);
  };

  exports.get = get;

  exports.set = set;

  exports.del = del;

  exports.init = init;

}).call(this);
