// Generated by CoffeeScript 1.3.3
(function() {
  var bot, callbackQueue, getProfile, init, profileGot, profiles, useridQueue;

  profiles = {};

  bot = null;

  init = function(_bot) {
    bot = _bot;
    return bot.on('update_user', function(data) {
      console.log('update_user');
      console.log(data);
      return delete profiles[data.userid];
    });
  };

  callbackQueue = [];

  useridQueue = [];

  getProfile = function(userid, callback) {
    console.log('request profile');
    if (typeof profiles[userid] !== 'undefined') {
      console.log('profile found retuning');
      return callback(profiles[userid]);
    }
    console.log('unknown profile');
    callbackQueue.push(callback);
    useridQueue.push(userid);
    return bot.getProfile(userid, profileGot);
  };

  profileGot = function(data) {
    var cb, userid;
    cb = callbackQueue.shift();
    userid = useridQueue.shift();
    profiles[userid] = data;
    return cb(data);
  };

  exports.getProfile = getProfile;

  exports.init = init;

}).call(this);
